### ISSUE TITLE
Comparison to other similar libraries

### ISSUE THREAD

**Issue by nikoladsp** [flexmock/flexmock#133]
Hi,
one question: I like flexmock, mainly because of it's easy of use and want to suggest it to my colleagues at work. Before I do that, I would like to know is there any comparison to other similar libraries I can show to them? Like what it does better then for example unittest's Mock and similar; so that it does not look I am proposing it just because I personally like it :)

Thank you in advance.

Best regards

**Comment by ollipa** [comment]
Hello! I'm glad to hear to you enjoy using flexmock. Did you notice the comparison section in the documentation?
https://flexmock.readthedocs.io/en/latest/compare/

**Comment by nikoladsp** [comment]
Thank you - I did not tbh; dived into usage straight ahead! Are there any good user reviews I can also show?

**Comment by ollipa** [comment]
I'm not sure if there are any user reviews I can point you to. If you want to compare flexmock to other libraries, take a look at [chainmock](https://github.com/ollipa/chainmock) and [pytest-mock](https://github.com/pytest-dev/pytest-mock/).

Chainmock has very similar API and uses Python standard library for mocks instead of custom mocking implementation. Chainmock also supports mocking async functions (that's the reason I started the project).

pytest-mock is also a wrapper for the standard library mocking functionality. It just exposes the standard library mocking in a way that is easier to use in pytest. If you like the API in flexmock, it might not be what you are looking for but pytest-mock is a lot more popular library than flexmock.

**Comment by nikoladsp** [comment]
Thank you very much - I will continue to use it and spread the good word!
