### ISSUE TITLE
Transfer of responsibility 

### ISSUE THREAD

**Issue by christophe-riolo** [flexmock/flexmock#41]
Hello,

We are using flexmock in our project, and I personally like it very much.

We have noticed however that there has been some time without activity on the Github repository, and as I have tried to make a PR, I was wondering at the same time if you would like to transfer the maintenance responsibility.
I tried to reach you by mail, but the address given on PyPI doesn't work.

**Comment by ghost** [comment]
@bkabrda, I'm also interested if you would be willing to add more maintainers or transfer the ownership of the project.

**Comment by bkabrda** [comment]
Hey folks, I am currently on PTO with limited internet access. I see that you have already created a new repo and I am fine with transferring ownership on PyPI as well. I should be back from PTO next Monday and I will update this issue so we can talk in more detail. Thanks!

**Comment by christophe-riolo** [comment]
Thank you this is really great news !

**Comment by bkabrda** [comment]
So I'm back from PTO and ready to talk.

First of all, thanks for reaching out and wanting to take this on. I still think this is a great library and would love to see it maintained, I just have no time to invest any more.

I saw that you already created https://github.com/flexmock/flexmock which is a bit unfortunate, because ideally I would transfer this repository to the org and then all the Github's redirects would work, which they won't now. I think it might still be best if you deleted that repository and let me transfer this repository to make this better.

I would also love to be a member of that new flexmock org. I might not have any time to commit now, but maybe I'll find some in the future and then I would definitely love to come back, so please consider inviting me there :)

In terms of PyPI access, please let me know who I should add as owners.

**Comment by christophe-riolo** [comment]
That sounds like a great idea, we'll delete the repository and invite you a bit later today.

In the mean time, Olli and I could take care of PyPI :
https://pypi.org/user/ollipa/
https://pypi.org/user/christophe-riolo/

Thanks for your answer!
Christophe Riolo Uusivaara

**Comment by christophe-riolo** [comment]
Hello,
Yestereve I deleted the repository and added you to the organisation as planned.

**Comment by bkabrda** [comment]
Hi @christophe-riolo 👋 I've just transfered the repository. Thanks! In terms of PyPI access, I've just noticed that I'm not an admin and can't manage access for it. The only admin is still the original author @has207 - Herman, could you make me an admin on PyPI so I could add more people there?

In the meanwhile, I can upload new releases if need be.

**Comment by ollipa** [comment]
@bkabrda, do you have owner access in Read The Docs? Are you able to add me to flexmock project in there? My username there is `ollipa`.

**Comment by has207** [comment]
@bkabrda made you an owner on pypi!

**Comment by bkabrda** [comment]
@has207 thanks a lot!

@christophe-riolo and @ollipa I've invited you on PyPI and I added @ollipa as maintainer on RTD.

**Comment by ollipa** [comment]
Thank you!

@christophe-riolo, I think we can close this issue now or is there something else we need?

**Comment by christophe-riolo** [comment]
Thank you!

Yes I'll close this issue!
